import { describe, it, expect, vi, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import type { BridgeHealthcheckResult, BridgeProbeResult } from '@chrischall/mcp-utils/fetchproxy';
import { webClient } from '../../src/web/client.js';
import { registerWebTools } from '../../src/tools/web.js';

/**
 * ta_web_healthcheck on a CDN/WAF refusal page (chrischall/mcp-host#1015): the
 * bridge did its job and came back with the edge's page, so the probe must
 * report `edge_blocked` with the vendor — not an unclassified failure.
 */
const CLOUDFRONT_403 = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
Request blocked.
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 7xXbE3cOQ2V0nY_example==
</PRE>
</BODY></HTML>`;

const BRIDGE = {
  role: 'host',
  port: 37149,
  server_version: '3.4.1',
  fetch_timeout_ms: 30000,
  last_success_at: null,
  last_failure_at: null,
  last_failure_reason: null,
  consecutive_failures: 0,
} as unknown as BridgeProbeResult['bridge'];

/** A started bridge whose runProbe runs the probe and files its throw as `other`, as the real one does for a non-bridge error. */
function fakeBridge() {
  return {
    async runProbe(fetchFn: (p: string) => Promise<string>, probePath: string): Promise<BridgeProbeResult> {
      try {
        await fetchFn(probePath);
        return { ok: true, elapsed_ms: 1, bridge: BRIDGE } as BridgeProbeResult;
      } catch (e) {
        return {
          ok: false,
          elapsed_ms: 1,
          bridge: BRIDGE,
          error: { kind: 'other', message: e instanceof Error ? e.message : String(e) },
        } as BridgeProbeResult;
      }
    },
    status: () => ({ role: 'host', port: 37149, lastExtensionMessageAt: null }),
  };
}

async function healthcheck(status: number, body: string): Promise<BridgeHealthcheckResult> {
  const bridge = fakeBridge();
  vi.spyOn(webClient, 'bridgeReady').mockResolvedValue(bridge as never);
  vi.spyOn(webClient, 'bridge').mockReturnValue(bridge as never);
  vi.spyOn(webClient, 'fetchRaw').mockResolvedValue({ status, body } as never);
  const h = await createTestHarness((s) => registerWebTools(s));
  try {
    return parseToolResult<BridgeHealthcheckResult>(await h.callTool('ta_web_healthcheck', {}));
  } finally {
    await h.close();
  }
}

afterEach(() => vi.restoreAllMocks());

describe('ta_web_healthcheck on a CDN/WAF block (mcp-host#1015)', () => {
  it('reports a CloudFront refusal page as edge_blocked with the vendor', async () => {
    const r = await healthcheck(403, CLOUDFRONT_403);
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail).toEqual({ vendor: 'CloudFront' });
    expect(r.hint).toMatch(/CDN\/WAF/);
  });

  it('control: a plain upstream 403 page is not called a block', async () => {
    const r = await healthcheck(403, '<html><head><title>403 Forbidden</title></head><body>nope</body></html>');
    expect(r.ok).toBe(false);
    expect(r.error?.kind).not.toBe('edge_blocked');
  });

  it('control: a healthy homepage reports ok', async () => {
    const r = await healthcheck(200, '<html><head><title>Tripadvisor</title></head><body>home</body></html>');
    expect(r.ok).toBe(true);
  });
});
